# -*- coding: utf-8 -*-
"""Range-Indexing-Slicing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SXda5OUaMU-25-jGZG5CJnOJG13Pb45I

**Range**
"""

numbers = range(21) # stop
print(numbers)
print(list(numbers))

genap = range(0,30,2) # start, stop, step
print(list(genap))

bilangan = range(50,101) # start, stop
print(list(bilangan))

"""**Indexing**"""

numbers2 = list(range(10, 21, 2))
print(numbers2)

print(numbers2[3])

print(numbers2[4])

print(numbers2[-1])

print(numbers2[-3])

"""**Slicing**"""

angka = list(range(10,101))
print(angka)

print(angka[:12]) # index 0 - index (12-1) - step 1 (by default)

print(angka[5:14]) # index 5 - index (14-1) - step 1 (by default)

print(angka[5:20:2]) # index 5 - index (20-1) - step

print(angka[:10:2]) # index 0 (by default) - index (10-1) - step 2

print(angka[5:]) # index 5 = index n (by default - step 1)

"""**Number Slicers**"""

# create a variable called 'numbers'
# creat a list of numbers 1 - 250 using list(range())

# print a number from index 15


# print an eight number from the back
# clue : negative indexing


# print a group of numbers, start from 55 until 67



# print a group of even numbers, starts from 70 until 240
# clue : use step parameter

numbers = list(range(1, 251))
print(numbers)

print(numbers[15])

print(numbers[-8])

print(numbers[55:67])

print(numbers[69:241:2])